### ISSUE TITLE
Constant Crashes

### ISSUE THREAD

**Issue by slooker** [exponentjs/react-native-image-picker-android#1]
I get crashes non stop when I have the image picker implemented.  Unfortunately I don't really have much more info than that.  As soon as I disabled it and removed the java changes I made, the app worked great again.

adb logcat gave me some info like so:

I hope this is useful. If there's anything else I can do to help debug, I'd be happy to.

[logcat.txt](https://github.com/exponentjs/react-native-image-picker-android/files/74601/logcat.txt)

This is on a Nexus 6p, running the stock firmware from Google Fi.

**Comment by slooker** [comment]
Oh, this is on a Nexus 6p, running the stock firmware from Google Fi.

**Comment by GedoonS** [comment]
Same here. Most of the time it works okay, but quite often, usually right after I've uploaded a new JS bundle and test the image picker, it crashes. Then when I start it again it will work again. 
When it crashes: I trigger the function, the camera opens, I can take the photo, I click the OK symbol but right after that I get the "unfortunately xyz has closed" and the app exits.

Edit: I'm testing with with a Motorola Moto G (3rd gen) device

**Comment by JonoH** [comment]
What options are you passing to the showImagePicker method? 

The workaround mentioned in #165 worked for me - basically removing any options that will result in the image re-sizing.
